NAMA : Mahesa Tirta Panjalu 
Kode : PYTN-KS18-012

In [1]:
import numpy as np

# Soal 1

In [10]:
start = int(input("Mulai : "))
end = int(input("Akhir : "))

arr = np.arange(start, end)
arr2 = arr.reshape(3,9)
arr3 = arr.reshape(3,3,3)

Mulai : 1
Akhir : 28


In [11]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

In [12]:
arr2

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24, 25, 26, 27]])

In [13]:
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

# Soal 2

In [17]:
jumlah = int(input('Banyak data : '))
start = int(input("Mulai : "))
end = int(input("Akhir : "))

arr = np.random.randint(start, end, jumlah)


Banyak data : 16
Mulai : 1
Akhir : 50


In [18]:
arr

array([21, 26, 25, 33, 19, 44, 26, 32,  6, 47, 27,  3, 25, 45, 43,  5])

In [19]:
arr.reshape(4,4)

array([[21, 26, 25, 33],
       [19, 44, 26, 32],
       [ 6, 47, 27,  3],
       [25, 45, 43,  5]])

In [21]:
arr.reshape(4,4)[:, ::-1]

array([[33, 25, 26, 21],
       [32, 26, 44, 19],
       [ 3, 27, 47,  6],
       [ 5, 43, 45, 25]])

# SOAL 3

In [23]:
arr = np.zeros((10,10))
print(arr)

arr[0, :] = 4
arr[-1, :] = 4
arr[:, 0] = 4
arr[:, -1] = 4


arr

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


array([[4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.]])